server:
  servlet:
    context-path: /adminex

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  #数据源:datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
    username: root
    password: cjx1125061985


    druid:
      aop-patterns: com.atguigu.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      web-stat-filter: # 监控web
        enabled: true  #开启 采集web-jdbc关联监控的数据 ，默认是false 需要手动在配置文件中开启
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      stat-view-servlet: # 配置监控页功能
        enabled: true
        login-username: ziqiu
        login-password: 123
        reset-enable: false

      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false






mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
